AWSTemplateFormatVersion: 2010-09-09
Description: >
  The IAM Role for command center instance
  Stack is named as ankcrimson-commandcenter-role
Resources:
  IAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      RoleName: ankcrimson.command.center

  ASGPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: ankcrimson-asg-all
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "autoscaling:*"
            Resource:
              - "*"
      Roles:
        - Ref: IAMRole


  CommandInstanceProfile:
      Type: "AWS::IAM::InstanceProfile"
      Properties:
        Path: "/"
        Roles:
          -
            Ref: "IAMRole"

